$('.navBar').on('mouseover',function()
{
  $(this).animate({
    width:'20vw'
  },300,'swing',function(){});
});
$('.navBar').on('mouseout',function()
{
  $(this).animate({
    width:'4vw'
  },200,'swing',function(){});
});
